### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by SavioAbdou** [SavioAbdou/IFT215-SavioAbdou#1]
how can I allow to add number in a text field without accepting any text value?

**Comment by SavioAbdou** [comment]
if i use this: 
if  (amount = 0) && (amount < 30000);
they said that I have an error. 
HAPPY NEW YEAR.

**Comment by eddyghabachlcu** [comment]
int amount = Integer.parseInt(txtAmount.getText().trim());
        if((rbCar.isSelected())&&((amount<0)||(amount>30000))){//write your condition here
           JOptionPane.showMessageDialog(this, "Car loan amount must be between 0 and 30000,","Warning",JOptionPane.WARNING_MESSAGE);
        }else if((rbHouse.isSelected())&&((amount<0)||(amount>300000))){
            JOptionPane.showMessageDialog(this, "House loan amount must be between 0 and 300000,","Warning",JOptionPane.WARNING_MESSAGE);
        }else{
            //Remaining code 
        }

**Comment by SavioAbdou** [comment]
Thank you. I forgot to use the operator "||".

I still have the result of monthly payment.
i created the code but i didn't know where to use it or if it's correct:

monthly payment	=   amount  +  (  amount	*  rate  * nbOfyear  )  /  (	12  *  nbOfyears  )

**Comment by eddyghabachlcu** [comment]
Take a look to the real estate project where we calculated the price within a method.
Then you call this method to print the value within the result amount field.

**Comment by SavioAbdou** [comment]
int nbOfyears= 
                    Integer.parseInt(
                            cbxYears.getSelectedItem().toString());
            
           JFormattedTextField rate = txtRate;
           
        
        
            ButtonGroup type = buttonGroup1;
        
            code re = 
                new code (amount,type,nbOfyears,rate);
          txtAmount2.setText(re.getMonthlypayment());
        }   


it is something like that ?
I got in error in the last line :        txtAmount2.setText(re.getMonthlypayment());

**Comment by eddyghabachlcu** [comment]
Because you have to convert it to string.
Try one of these:
txtAmount2.setText(Integer.toString(re.getMonthlypayment()));
OR
txtAmount2.setText(String.valueOf(re.getMonthlypayment()));

**Comment by SavioAbdou** [comment]
something wrong I will sync it

**Comment by eddyghabachlcu** [comment]
Yes of course, the parameters that you are sending to the constructor aren't of the same type of the constructor's parameters. In addition, you added some EXTRA code everywhere. You have to understand each instruction what it is going to do, and how to use it.

**Comment by SavioAbdou** [comment]
if I wrote for the rate integer in the Jframe source, they told me that there is an error.
in the main the rate is integer.
where is the problem in this thing?

**Comment by eddyghabachlcu** [comment]
show me the  code!

**Comment by SavioAbdou** [comment]
JFrame Code:

    int nbOfyears= 
                    Integer.parseInt(
                            cbxYears.getSelectedItem().toString());
            
           int rate;
            rate = txtRate;
           
        
        
            ButtonGroup type = buttonGroup1;
        
            code re = 
                new code (amount,type,nbOfyears,rate);
txtAmount2.setText(String.valueOf(re.getMonthlypayment()));



main code:
package project;

public class code{
	private int amount;
    	private String type;
    	private int nbOfyears;
    	private int rate;
    	private static final String bankName="Bank of Beirut";
    
    public code(int amount, String type, 
            int nbOfYears, int rate){
        this.amount=amount;
        this.type=type;
        this.nbOfyears=nbOfyears;
        this.rate=rate;
    }

    
    public int getAmount(){
        return amount;
    }
    
    public void setAmount(int amount){
        this.amount=amount;
    }
    
    public String getType(){
        return type;
    }
    
    public void setType(String type){
        this.type=type;
    }
    
    public int getnbOfYears(){
        return nbOfyears;
    }
    
    public void setnbOfyears(int nbOfyears){
        this.nbOfyears=nbOfyears;
    }
    
    public int getRate(){
        return rate;
    }
    
    public void setRate(int rate){
        this.rate=rate;
    }
    
    public int getMonthlypayment(){
        int month=12; int monthlyPayment;
        monthlyPayment = amount + (amount*rate*nbOfyears)/(month*nbOfyears);
                return monthlyPayment;
    }


}

**Comment by eddyghabachlcu** [comment]
JFrame code is wrong:

        int rate;
        rate = txtRate;
        ButtonGroup type = buttonGroup1;

rate should be equal to the txtRate.getText() and type should be a String and its value should be assigned based on the radio button selected.

**Comment by SavioAbdou** [comment]
i got this error :
incompatible types: Boolean cannot be converted to String.

in this line:
               new code (amount,type,nbOfyears,rate);
       txtAmount2.setText(Integer.toString(re.getMonthlypayment()));

**Comment by eddyghabachlcu** [comment]
commit and synch

**Comment by eddyghabachlcu** [comment]
String rate = txtRate.getText();
Should be
int rate = Integer.parseInt(txtRate.getText());

**Comment by eddyghabachlcu** [comment]
And type should be:

String type="";

if(rbCar.isSelected()){
type="Car";
}else{
type="Bank";
}

**Comment by SavioAbdou** [comment]
something wrong.

**Comment by eddyghabachlcu** [comment]
where?!

**Comment by SavioAbdou** [comment]
I didn't got the result when executing it

**Comment by SavioAbdou** [comment]
I didn't got the result while running it

**Comment by eddyghabachlcu** [comment]
synch and commit!!!

**Comment by SavioAbdou** [comment]
done

**Comment by eddyghabachlcu** [comment]
In JFrame code.
Line 3 correct:
import com.sun.glass.events.KeyEvent; 
TO
import java.awt.event.KeyEvent;
Line 258 correct:
if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACKSPACE) || c==KeyEvent.VK_DELETE)){
TO
if(!(Character.isDigit(c) || (c==KeyEvent.VK_ENTER) || c==KeyEvent.VK_DELETE)){

**Comment by SavioAbdou** [comment]
same error

**Comment by eddyghabachlcu** [comment]
recommit and synch

**Comment by eddyghabachlcu** [comment]
Can you clarify something for me please.
Is your project failing to compile?
If yes,
Which version of NetBeans you are using?
And which version of JDK? (go to command prompt and write: java -version)

**Comment by eddyghabachlcu** [comment]
In your constructor correct this:
this.nbOfyears=nbOfyears;
TO
this.nbOfyears=nbOfYears;

**Comment by SavioAbdou** [comment]
NetBeans IDE 8.0.2
java version 1.8.0_25

**Comment by eddyghabachlcu** [comment]
Ok so after correcting nbOfYears variable, your project should work without errors. That doesn't guarantee that it will work correctly it's up to you to see.

**Comment by SavioAbdou** [comment]
it's work.
but I still have one problem in the result the code is correct I checked up

monthlyPayment= (amount+(amount*(rate/100)*nbOfyears))/(12*nbOfyears);


it's only calculate: amount / (12*nbOfyears) - Only.

**Comment by eddyghabachlcu** [comment]
good

**Comment by SavioAbdou** [comment]
how to fix it ?

**Comment by eddyghabachlcu** [comment]
I let you think about it!

**Comment by SavioAbdou** [comment]
something in monthlyPayment or the GUI code?

**Comment by eddyghabachlcu** [comment]
Read your code carefully, track it, each instruction, do some test cases and you will discover where

**Comment by SavioAbdou** [comment]
I just need something 
what should I do to wen I press enter I got the result
I used the         rootPane.setDefaultButton(btnSubmit);

**Comment by eddyghabachlcu** [comment]
If your button name is btnSubmit it will work, if not you must replace btnSubmit by the button name

**Comment by SavioAbdou** [comment]
it didn't work
